
spring:
  profiles: dev
  thymeleaf:
    cache: false

profileName: Development

logging:
  level:
    org.springframework: INFO
---
spring:
  profiles: pro
  thymeleaf:
      cache: true

profileName: Production